dbt_airlinedata:
  outputs:
    dev_hive:
      type: hive
      use_http_transport: true
      use_ssl: true
      auth_type: ldap #now also support kerberos
      schema: "dbt_airlinedata_demo"
      user: "frothkoetter"
      password: "password"
      host: "cdw-host"
      port: 443 
      http_path: "url-"
      threads: 2
  target: dev_hive
