dbt_airlinedata:
  outputs:
#  Development Output
    dev_hive:
      type: hive
      use_http_transport: true
      use_ssl: true
      auth_type: ldap #now also support kerberos
      schema: "dbt_airlinedata_demo"
      user: "frothkoetter"
      password: "{{ env_var('WORKLOAD_PASSWORD') }}"
      host: hs2-cdw-aw-se-hive.dw-se-sandbox-aws.a465-9q4k.cloudera.site
      port: 443
      http_path: "jdbc:hive2://hs2-cdw-aw-se-hive.dw-se-sandbox-aws.a465-9q4k.cloudera.site/default;transportMode=http;httpPath=cliservice;socketTimeout=60;ssl=true;auth=browser;"
      threads: 2

#  Production Output
    prod_hive:
      type: hive
      use_http_transport: true
      use_ssl: true
      auth_type: ldap
      schema: "dbt_airlinedata" # Production-ready schema name
      user: "frothkoetter"      # Suggestion: Use a service account for prod
      password:  "{{ env_var('WORKLOAD_PASSWORD') }}"
      host: hs2-cdw-aw-se-hive.dw-se-sandbox-aws.a465-9q4k.cloudera.site
      port: 443
      http_path: "jdbc:hive2://hs2-cdw-aw-se-hive.dw-se-sandbox-aws.a465-9q4k.cloudera.site/default;transportMode=http;httpPath=cliservice;socketTimeout=60;ssl=true;auth=browser;"
      threads: 4

  target: dev_hive # Keeps dev as default to prevent accidental prod runs
